### ISSUE TITLE
Complete the solving problems multiverse curriculum module 1

### ISSUE THREAD

**Issue by laracardonamorisset** [laracardonamorisset/Problem-Solving-Challenges#1]
## Tasks:
- [ ] Create a repository for problem solving challenges
- [ ] Solve the first problem
- [ ] Solve the second problem
- [ ] Solve the third problem
- [ ] Solve the fourth problem
- [ ] Solve the fifth problem
- [ ] 

## Notes:
know what "done" is in order to concretize the task

https://publish.obsidian.md/themultiverseschool/Curriculum/Technomancy/Algorithms/Intro+to+Problem+Solving+Module

learning to code:
concrete and abstract level 9 or 10

https://publish.obsidian.md/themultiverseschool/Curriculum/Technomancy/Algorithms/Intro+to+Problem+Solving+Module
12 level to 8/9 level

swimming downwards from upper to lower levels of complexity

todo = formal and below level
