### ISSUE TITLE
Complete the solving problems multiverse curriculum Module 2

### ISSUE THREAD

**Issue by laracardonamorisset** [laracardonamorisset/Problem-Solving-Challenges#2]
To complete after #1 

## Tasks:
- [ ] Complete 1st problem
- [ ] Complete 2nd problem
- [ ] Complete 3rd problem
- [ ] Complete 4th problem
- [ ] Complete 5th problem
- [ ] Complete 6th problem
